/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Booking {
  'id' : bigint,
  'packageType' : PackageType,
  'name' : string,
  'email' : string,
  'message' : string,
  'preferredDate' : string,
  'timestamp' : bigint,
  'phone' : string,
  'numberOfGuests' : bigint,
}
export interface Contact {
  'id' : bigint,
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : bigint,
}
export type PackageType = { 'vip' : null } |
  { 'premium' : null } |
  { 'standard' : null };
export interface _SERVICE {
  'addItemToCart' : ActorMethod<[bigint], undefined>,
  'getAllBookings' : ActorMethod<[], Array<Booking>>,
  'getAllContacts' : ActorMethod<[], Array<Contact>>,
  'removeItemFromCart' : ActorMethod<[bigint], undefined>,
  'submitBooking' : ActorMethod<
    [string, string, string, string, PackageType, bigint, string],
    undefined
  >,
  'submitContact' : ActorMethod<[string, string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];