/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PackageType = IDL.Variant({
  'vip' : IDL.Null,
  'premium' : IDL.Null,
  'standard' : IDL.Null,
});
export const Booking = IDL.Record({
  'id' : IDL.Nat,
  'packageType' : PackageType,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'preferredDate' : IDL.Text,
  'timestamp' : IDL.Int,
  'phone' : IDL.Text,
  'numberOfGuests' : IDL.Nat,
});
export const Contact = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
});

export const idlService = IDL.Service({
  'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getAllContacts' : IDL.Func([], [IDL.Vec(Contact)], ['query']),
  'submitBooking' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, PackageType, IDL.Nat, IDL.Text],
      [],
      [],
    ),
  'submitContact' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PackageType = IDL.Variant({
    'vip' : IDL.Null,
    'premium' : IDL.Null,
    'standard' : IDL.Null,
  });
  const Booking = IDL.Record({
    'id' : IDL.Nat,
    'packageType' : PackageType,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'preferredDate' : IDL.Text,
    'timestamp' : IDL.Int,
    'phone' : IDL.Text,
    'numberOfGuests' : IDL.Nat,
  });
  const Contact = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  
  return IDL.Service({
    'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getAllContacts' : IDL.Func([], [IDL.Vec(Contact)], ['query']),
    'submitBooking' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          PackageType,
          IDL.Nat,
          IDL.Text,
        ],
        [],
        [],
      ),
    'submitContact' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };